[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''


[tool.isort]
profile = "black"
multi_line_output = 3
default_section = "THIRDPARTY"
known_first_party = []
force_grid_wrap = 0
line_length = 120
known_third_party = ["celery", "django", "django_filters", "drf_misc", "rest_framework", "rest_framework_extensions"]
